version: "3.8"

services:
  frontend:
    image: fr4cas/blueprint-frontend
    container_name: blueprint-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    image: fr4cas/blueprint-backend
    container_name: blueprint-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped