version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: blueprint-backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    restart: unless-stopped